name: Build Debug APK

on:
  pull_request_review:
    paths-ignore:
      - '**.md'
    types: submitted
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload the APK
        uses: actions/upload-artifact@v4
        with:
          name: EasyNotes-debug
          path: app/build/outputs/apk/debug/app-debug*.apk
